### PR TITLE
SBL Hebrew font

### LINKED ISSUE #141: Set Font for Hebrew
The Hebrew font on git.door43.org is a bit rough to read.  Let's set the default to [SBL Hebrew](https://www.sbl-site.org/educational/BiblicalFonts_SBLHebrew.aspx) with a fall back to GentiumAlt, then to Noto Sans.

### PR DESCRIPTION
**Pull request by ethantkoenig**
Fixes #141. Two minor points:
1. I was unable to add fallbacks to `GentiumAlt` or `NotoSans`, since I'm not sure there's a way to have built-in font families only apply to certain character ranges. Since we're providing our own `.ttf/.woff` file for SBL Hebrew, I don't anticipate that fallback will be a frequent issue.
2. This won't work on Opera Mini (which I assume we don't support?)

### CODE REVIEW

**Comment by ethantkoenig** [comment]
@phillip-hopper Not that I know of, since it has to do with how the browser renders the page, not any specific HTML component that we could check for.

**Comment by phillip-hopper** [comment]
Is there a way I can see it in action if I run gogs locally?

**Comment by phillip-hopper** [comment]
@ethantkoenig It looks like it may not be quite right.

**Comment by ethantkoenig** [comment]
@phillip-hopper Isn't that the intended behavior? I had thought we only want to use SBL Hebrew for Hebrew characters (i.e. unicode range `590-5FF`), not for all characters?

**Pull request merged**
