### PR TITLE
UI tweaks to 'View on Door43' button

### PR DESCRIPTION
**Pull request by ethantkoenig**
The inconsistency of having a shadowed, unaligned "View on Door43" button has been bothering me for a while, so I decided to fix it. I also added an icon for consistency with the Watch/Star/Fork buttons; if you think a different icon would be more appropriate, Iet me know.

I took the opportunity to clean-up some inline css, and make our `template/repo/header.tmpl` more in-sync with upstream's, to mitigate future merge conflicts. I also introduced `public/less/_unfoldingWord.less`, where we can keep styling changes specific to our fork.

Before:
image

After:
image

### CODE REVIEW

**Comment by richmahn** [comment]
The shadowed button was actually what the design called for. @jag3773 should verify this change.

**Comment by jag3773** [comment]
@ethantkoenig Let's update this so that the text of the button is "See on Door43" and then move the Door43 icon to the left where the fa book icon currently is.

**Comment by ethantkoenig** [comment]
@jag3773 Done (see updated screenshot in description). Also added a locale for "See on Door43"

**Comment by jag3773** [comment]
@ethantkoenig Looks great, but there appears to be a minor vertical alignment issue inside the button between the text and the icon.  Would shrinking the Door43 icon just a bit fix that?

**Comment by ethantkoenig** [comment]
@jag3773 Done. I couldn't find a super clean way to do it (typically I would use flexbox for vertical alignment, but that caused the button's text to be misaligned with the other buttons' text), so I resorted to fiddling with the image margins.

**Pull request merged**
