### PR TITLE
Merge upstream changes

### PR DESCRIPTION
**Pull request by ethantkoenig**
Also updates our `.travis.yml` to accomodate merged changes to coverage reports.

### CODE REVIEW

**Comment by jag3773** [comment]
@ethantkoenig Does this include code from 1.3 upstream?

**Comment by ethantkoenig** [comment]
@jag3773 Yes, that's why I've targeted `develop`, not the release branch.

**Comment by jag3773** [comment]
heh.. good work!  Except that I've been building off the `develop` branch for my testing!

I'm considering merging this in anyway and continuing testing against a 1.3 build.  What do you think?  Are there changes that may cause problems with our setup if I do that?

**Comment by jag3773** [comment]
I'm going to merge this in and run it through our initial testing.  If there are major problems, I put a tag and a build up at https://github.com/unfoldingWord-dev/gogs/releases/tag/v1.2.03 which points to our work so far.  We can easily use that directly or make bugfixes against it if needed.

**Pull request merged**
