### PR TITLE
UI tweaks for 'See on Door43' button

### PR DESCRIPTION
**Pull request by ethantkoenig**
Even with https://github.com/unfoldingWord-dev/gogs/commit/d2d0de417140a43ecbc110d466edde3120057692, the 'See on Door43' button isn't quite consistent with the Watch/Fork/Star buttons (it's about 1px shorter). The only way I could find to ensure that the buttons have the same height (without resorting to a ridiculous hack) was to add a label to the 'See on Door43' button.

Other tweaks:
- I added a little separation between the 'See on Door43' button and the Watch/Fork/Star buttons.
- I made the 'See on Door43' label pointed, to distinguish it from the Watch/Forks/Star labels which serve as counts.

Before:
image

After:
image

### CODE REVIEW

**Comment by richmahn** [comment]
@ethantkoenig Had noticed this 1px difference, due to the border of the numbers in the other buttons, yet also couldn't figure out a fix...adding a border to the inside of the Door43 button made it too big. @jag3773 Does this look ok?

**Comment by richmahn** [comment]
@ethantkoenig The right of the Door43 button has a bit more margin than others. Is that intentional?

**Comment by ethantkoenig** [comment]
@richmahn Yes (first bullet in the description :smile:)

**Comment by richmahn** [comment]
@ethantkoenig Oops! Missed that. Yeah, that is good though...a little separate.

**Pull request merged**
